CREATE DATABASE project_db;
USE project_db;

CREATE TABLE customer (
    `Customer ID` INT,
    `Age` INT,
    `Gender` VARCHAR(10),
    `Item Purchased` VARCHAR(100),
    `Category` VARCHAR(50),
    `Purchase Amount (USD)` DECIMAL(10,2),
    `Location` VARCHAR(50),
    `Size` VARCHAR(10),
    `Color` VARCHAR(20),
    `Season` VARCHAR(20),
    `Review Rating` VARCHAR(20),
    `Subscription Status` VARCHAR(10),
    `Shipping Type` VARCHAR(20),
    `Discount Applied` VARCHAR(10),
    `Promo Code Used` VARCHAR(10),
    `Previous Purchases` INT,
    `Payment Method` VARCHAR(20),
    `Frequency of Purchases` VARCHAR(20)
);

LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/customer_shopping_behavior.csv'
INTO TABLE customer
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM customer ;

-- Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased,
ROUND(AVG(CAST(review_rating AS DECIMAL(10,2))),2) AS avg_product_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_product_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount),2) AS avg_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer
)

SELECT customer_segment,
       COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(*) AS total_orders
    FROM customer
    GROUP BY category, item_purchased
),

ranked_items AS (
    SELECT category,
           item_purchased,
           total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY total_orders DESC
           ) AS item_rank
    FROM item_counts
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM ranked_items
WHERE item_rank <= 3;


-- Q9. Are repeat buyers (more than 5 previous purchases) likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;